# Generated by Django 5.0 on 2023-12-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='timestamp',
        ),
    ]
